import type { Product } from "@/lib/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p-1",
    name: 'MacBook Pro 14"',
    sku: "MBP14M3PRO",
    description: "Laptop z procesorem M3 Pro i ekranem Liquid Retina XDR.",
    producer: "Apple",
    category: "Komputery",
    features: ["Bluetooth", "WiFI", "USB-C", "Premium"],
    priceGross: 9999,
    vatRate: "23",
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minQuantity: 1,
    maxQuantity: 5,
  },
  {
    id: "p-2",
    name: "Galaxy S24 Ultra",
    sku: "SGS24U256",
    description: "Smartfon 256 GB z tytanową ramką.",
    producer: "Samsung",
    category: "Telefony",
    features: ["Bluetooth", "WiFI", "USB-C", "Wodoodporny"],
    priceGross: 6299,
    vatRate: "23",
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 45,
    minQuantity: 1,
    maxQuantity: 10,
  },
  {
    id: "p-3",
    name: "Sony WH-1000XM5",
    sku: "SNWH1000XM5",
    description: "Bezprzewodowe słuchawki z aktywną redukcją szumów.",
    producer: "Sony",
    category: "RTV",
    features: ["Bluetooth", "Bezprzewodowy", "USB-C"],
    priceGross: 1599,
    vatRate: "23",
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minQuantity: 1,
    maxQuantity: 10,
  },
  {
    id: "p-4",
    name: "Bosch Serie 6 WAU28P40",
    sku: "BSWAU28P40",
    description: "Pralka ładowana od frontu, 9 kg.",
    producer: "Bosch",
    category: "AGD",
    features: ["Ekologiczny"],
    priceGross: 3299,
    vatRate: "23",
    currency: "PLN",
    isAvailable: false,
    isLimited: true,
    stockQuantity: 0,
    minQuantity: 1,
    maxQuantity: 2,
  },
  {
    id: "p-5",
    name: "Xiaomi Smart Band 8",
    sku: "XMSB8BLK",
    description: "Opaska sportowa z pomiarem tętna i SpO2.",
    producer: "Xiaomi",
    category: "Akcesoria",
    features: ["Bluetooth", "Wodoodporny"],
    priceGross: 179,
    vatRate: "23",
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minQuantity: 1,
    maxQuantity: 10,
  },
  {
    id: "p-6",
    name: "LG OLED evo C4 55",
    sku: "LGOLED55C4",
    description: "Telewizor OLED 55 cali, 120 Hz.",
    producer: "LG",
    category: "RTV",
    features: ["WiFI", "Bluetooth", "Premium"],
    priceGross: 5499,
    vatRate: "23",
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 12,
    minQuantity: 1,
    maxQuantity: 3,
  },
  {
    id: "p-7",
    name: "Philips Series 5000 HD9280",
    sku: "PHHD9280",
    description: "Frytkownica beztłuszczowa 6,2 l.",
    producer: "Philips",
    category: "AGD",
    features: ["Ekologiczny", "Premium"],
    priceGross: 898,
    vatRate: "23",
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minQuantity: 1,
    maxQuantity: 10,
  },
];
